// Mocks generated by Mockito 5.4.6 from annotations
// in todo_list/test/viewmodels/edit_task_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_list/models/task_model.dart' as _i4;
import 'package:todo_list/services/task/task_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i2.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addTask(_i4.TaskModel? task, {_i5.Uint8List? imageBytes}) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task], {#imageBytes: imageBytes}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTask(
    _i4.TaskModel? task, {
    _i5.Uint8List? imageBytes,
    bool? removeImage = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTask,
              [task],
              {#imageBytes: imageBytes, #removeImage: removeImage},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.TaskModel?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i3.Future<_i4.TaskModel?>.value(),
          )
          as _i3.Future<_i4.TaskModel?>);

  @override
  _i3.Stream<List<_i4.TaskModel>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i3.Stream<List<_i4.TaskModel>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskModel>>);

  @override
  _i3.Stream<List<_i4.TaskModel>> getTasksByCategory(
    _i4.TaskCategory? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByCategory, [category]),
            returnValue: _i3.Stream<List<_i4.TaskModel>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskModel>>);

  @override
  _i3.Stream<List<_i4.TaskModel>> searchTasks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [query]),
            returnValue: _i3.Stream<List<_i4.TaskModel>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskModel>>);
}
